#!/usr/bin/env bash
# build.sh — Compiles individual rule files from rules/ into AGENTS.md
# Usage: ./scripts/build.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
RULES_DIR="$SKILL_DIR/rules"
OUTPUT="$SKILL_DIR/references/COMPILED-GUIDE.md"

# Category ordering and metadata
declare -A SECTIONS=(
  [1]="A01:2025 — Broken Access Control|access-"
  [2]="A02:2025 — Security Misconfiguration|config-"
  [3]="A03:2025 — Software Supply Chain Failures|supply-"
  [4]="A04:2025 — Cryptographic Failures|crypto-"
  [5]="A05:2025 — Injection|inject-"
  [6]="A06:2025 — Insecure Design|design-"
  [7]="A07:2025 — Authentication Failures|auth-"
  [8]="A08:2025 — Software or Data Integrity Failures|integrity-"
  [9]="A09:2025 — Security Logging and Alerting Failures|logging-"
  [10]="A10:2025 — Mishandling of Exceptional Conditions|error-"
)

# Header
cat > "$OUTPUT" << 'HEADER'
# OWASP Security Patterns — Top 10 2025

Comprehensive security guide for React, Node.js, Azure, and cloud-native
development. Based on the OWASP Top 10:2025 analysis of 175,000+ CVEs.

> This file is auto-generated by `scripts/build.sh` from individual rule
> files in `rules/`. Do not edit directly.

---
HEADER

rule_count=0

for i in $(seq 1 10); do
  IFS='|' read -r section_title prefix <<< "${SECTIONS[$i]}"

  echo "" >> "$OUTPUT"
  echo "## $section_title" >> "$OUTPUT"
  echo "" >> "$OUTPUT"

  # Find and sort rule files for this prefix
  for rule_file in $(find "$RULES_DIR" -name "${prefix}*.md" ! -name '_*' | sort); do
    echo "" >> "$OUTPUT"
    # Strip frontmatter (if any) and append content
    if head -1 "$rule_file" | grep -q '^---$'; then
      # Has frontmatter — skip it
      sed -n '/^---$/,/^---$/!p' "$rule_file" | tail -n +1 >> "$OUTPUT"
    else
      cat "$rule_file" >> "$OUTPUT"
    fi
    echo "" >> "$OUTPUT"
    echo "---" >> "$OUTPUT"
    rule_count=$((rule_count + 1))
  done
done

echo ""
echo "Built AGENTS.md with $rule_count rules from $RULES_DIR"
echo "Output: $OUTPUT"
